name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        rosdistro:
          - humble

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}

      - name: Setup directories
        run: mkdir -p ros2_ws/src

      - name: Copy source code
        run: cp -r . ros2_ws/src/ros2_topic_sample

      - name: Install dependencies
        run: |
          cd ros2_ws
          sudo apt-get update
          rosdep update
          rosdep install --from-path src -i -y --rosdistro ${{ matrix.rosdistro }}

      - name: Build tests
        id: build_test
        run: |
          cd ros2_ws
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon build
        continue-on-error: true

      - name: build_test command success
        if: steps.build_test.outcome == 'success'
        run: echo "result - success"

      - name: build_test command failure
        if: steps.build_test.outcome == 'failure'
        run: echo "result - failure" && exit 1

      - name: Run tests
        id: run_test
        run: |
          cd ros2_ws
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          colcon test
          colcon test-result
        continue-on-error: true

      - name: run_test command success
        if: steps.run_test.outcome == 'success'
        run: echo "result - success"

      - name: run_test command failure
        if: steps.run_test.outcome == 'failure'
        run: echo "result - failure" && exit 1
