name: Build and run ROS2 tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        rosdistro: [ humble ]

    runs-on: ubuntu-latest

    continue-on-error: true

    container:
      # There don't seem to be ROS perception docker images for ros2 yet, so we
      # use the base imageand install the rest of the dependencies using rosdep
      # each time.
      image: ros:${{ matrix.rosdistro }}-ros-base

    steps:
    - uses: actions/checkout@v2
      with:
        path: src/ros2_topic_sample

    - name: Install dependencies
      run: rosdep update --include-eol-distros && apt-get update && rosdep install --from-path . -i -y --rosdistro ${{ matrix.rosdistro }}

    - name: Install diagnostic-updater
      run: apt-get install ros-${{ matrix.rosdistro }}-diagnostic-updater

    - name: Build tests
      run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon build --event-handlers console_cohesion+

#     - name: Run tests
#       run: . /opt/ros/${{ matrix.rosdistro }}/setup.sh && colcon test --event-handlers console_cohesion+ && colcon test-result
